
---
#     add-apt-repository ppa:phoerious/keepassxc
# apt update
# apt install keepassxc

    - name: Add Albert repository
      apt_repository: repo="ppa:phoerious/keepassxc" state=present

    - name: Install KeepassXC
      apt: pkg=keepassxc state=latest update_cache=yes