

# Future state, not essential for first pass 
    # Verify that you now have the key with the fingerprint 9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88, by searching for the last 8 characters of the fingerprint.

    # $ sudo apt-key fingerprint 0EBFCD88
        
    # pub   rsa4096 2017-02-22 [SCEA]
    #       9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
    # uid           [ unknown] Docker Release (CE deb) <docker@docker.com>
    # sub   rsa4096 2017-02-22 [S]
    
    # sudo add-apt-repository \
    # "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    # $(lsb_release -cs) \
    # stable"

# https://docs.docker.com/install/linux/docker-ce/ubuntu/

---
    # TODO: replace impl with Ansible best practice
    # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: Installing apt-key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
    
    - name: Add deb repository
    # ansible_distribution_release should equal bionic
      apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' state=present
    
    - name: Install Docker
      apt: pkg="{{ item }}" state=latest update_cache=yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    
    - name: Create Docker group
      group: name=docker state=present
    
    - name: Add current user to Docker group
      user: name="{{ ansible_env.USER }}" groups=docker append=yes
    
    - name: "Ensure Docker is started"
      service: name=docker state=restarted enabled=no